import { pgTable, uuid, text, boolean, integer, timestamp, jsonb } from "drizzle-orm/pg-core";

export const communities = pgTable("communities", {
  id: uuid("id").defaultRandom().primaryKey(),
  classification: text("classification"),
  status: text("status", { enum: ["open", "closed"] }).default("open").notNull(),
  address: text("address").notNull(),
  city: text("city").notNull(),
  state: text("state").notNull(),
  zip: text("zip").notNull(),
  phone: text("phone"),
  email: text("email"),
  isAbuseFree: boolean("is_abuse_free"),
  isViolationFree: boolean("is_violation_free"),
  licenseNumber: text("license_number"),
  firstname: text("firstname"),
  lastname: text("lastname"),
  genderRestriction: text("gender_restriction", { enum: ["male", "female", "both"] }),
  hasMedicaidContract: boolean("has_medicaid_contract"),
  medicaidSpendDown: text("medicaid_spend_down"),
  monthlyBasePrice: integer("monthly_base_price"),
  monthlyHighPrice: integer("monthly_high_price"),
  careServices: jsonb("care_services").$type<string[]>(),
  communityRating: integer("community_rating"),
  communityRatingReason: text("community_rating_reason"),
  communityNarrative: text("community_narrative"),
  title: text("title"),
  website: text("website"),
  description: text("description"),
  images: jsonb("images").$type<string[]>(),
  videos: jsonb("videos").$type<string[]>(),
  documents: jsonb("documents").$type<string[]>(),
  links: jsonb("links").$type<string[]>(),
  tags: jsonb("tags").$type<string[]>(),
  smsOptIn: boolean("sms_opt_in"),
  joinedAt: timestamp("joined_at"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
});

export const customers = pgTable("customers", {
  id: uuid("id").defaultRandom().primaryKey(),
  firstName: text("first_name").notNull(),
  lastName: text("last_name").notNull(),
  email: text("email").notNull(),
  mobilePhone: text("mobile_phone"),
  status: text("status", {
    enum: ["new", "qualified", "searching", "placed", "moved", "invoiced", "closed"],
  }).default("new").notNull(),
  closedReason: text("closed_reason", {
    enum: ["paid", "deceased", "terminated", "duplicate", "financial_inability", "other"],
  }),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
});
